# Generated by Django 5.2.5 on 2026-01-20 06:57

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsersettings',
            name='city',
            field=models.CharField(default='Москва', max_length=100, verbose_name='Город поиска', help_text='Город для поиска товаров (например: Москва, Санкт-Петербург, Краснодар)', blank=True),
        ),
    ]