# Generated by Django 5.2.5 on 2026-01-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20260120_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='parse_time_display',
            field=models.CharField(blank=True, default='0:00', help_text='Время в формате ММ:СС', max_length=20, verbose_name='Время парсинга'),
        ),
        migrations.AddField(
            model_name='founditem',
            name='parse_time_seconds',
            field=models.IntegerField(default=0, verbose_name='Длительность парсинга (секунды)'),
        ),
        migrations.AddField(
            model_name='founditem',
            name='search_duration_seconds',
            field=models.IntegerField(default=0, verbose_name='Длительность поиска (секунды)'),
        ),
        migrations.AddField(
            model_name='founditem',
            name='time_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Статус скорости обработки'),
        ),
        migrations.AddField(
            model_name='founditem',
            name='total_processing_seconds',
            field=models.IntegerField(default=0, verbose_name='Общее время обработки (секунды)'),
        ),
    ]
