# Generated by Django 5.2.5 on 2026-01-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_founditem_parse_time_display_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todocard',
            options={'ordering': ['-priority', 'card_order', 'created_at'], 'verbose_name': 'Карточка задачи', 'verbose_name_plural': 'Карточки задач'},
        ),
        migrations.AddField(
            model_name='todocard',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Низкий'), (2, 'Обычный'), (3, 'Высокий'), (4, 'Критический')], default=2, verbose_name='Важность'),
        ),
    ]
