# Generated by Django 5.2.5 on 2026-01-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_todocard_options_todocard_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todocard',
            name='error_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='todocard',
            name='task_type',
            field=models.CharField(choices=[('error', 'Ошибка'), ('warning', 'Предупреждение'), ('fix', 'Исправление'), ('refactor', 'Рефакторинг'), ('test', 'Тестирование'), ('feature', 'Новая функция'), ('documentation', 'Документация'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип задачи'),
        ),
    ]
